@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

LAYOUT_WITH_LEGEND()

title System Context diagram for Face Frenzy(Not sexual)

Person(user, "Player", "A user of this system, player. Could be multiple people, with no different accounts")
Person(Juadmin, "Juadmin", "Developer of the system, and review of anaylitcs data through the web server")
System(game, "Internet Banking System", "Allows customers to view information about their bank accounts, and make payments.")
 
System_Ext(Camera, "E-mail system", "The internal Microsoft Exchange e-mail system.")
System_Ext(Display, "E-mail system", "The internal Microsoft Exchange e-mail system.")
System_Ext(Webserver, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.")

Rel(user, game, "Uses")
Rel_Back(user, mail_system, "Sends e-mails to")
Rel_Neighbor(game, mail_system, "Sends e-mails", "SMTP")
Rel(game, mainframe, "Uses")
@enduml