@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

LAYOUT_WITH_LEGEND()

title System Context diagram for Face Frenzy

Person(User, "Player", "A user of this system, player. Could be multiple people, with no different accounts")
Person(Admin, "Admin", "Developer of the system, and review of anaylitcs data through the web server")
System(Game, "Face Frenzy Game", "The Game, where just the right amount of faces have to be shown")
 
System_Ext(Camera, "Camera", "The camera, where the game precieves the room from")
System_Ext(Display, "Display", "The hardware, where the game displays information")
System_Ext(PYNQ, "PYNQ Board", "Hardware, where the game run")

Rel(Display, User, "Shows the game")
Rel(Camera, User, "Percieves Faces")

Rel(Game, Admin, "Displays Analytics")
Rel(Admin, Game, "Makes Changes")

Rel(Game, PYNQ, "Is run on")
Rel(PYNQ, Display, "Sends information to show")
Rel(PYNQ, Camera, "Recieves picture to process")
@enduml