@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include <C4/C4_Component.puml>

LAYOUT_WITH_LEGEND()

title Component diagram for Face Frenzy - API Application

System_Ext(camera, "Camera", "Captures images of the player")
System_Ext(display, "Display", "Display the game")

Container_Boundary(api, "API Application") {
    Component(cameraManager, "Camera Manager", "Python or OpenCV", "Initialize and manage webcam input and capture frames periodically")
    Component(faceDetector, "Face Detector", "OpenCV", "Process captured frames, to detect faces using OpenCV and return the number of faces detected")
    Component(simpleOutputManager, "Simple Output Manager", "Python", "Display face count, initially with simple terminal interface, later with HDMI overlay")

    Rel(cameraManager, faceDetector, "Images for processing")
    Rel(faceDetector, simpleOutputManager, "Information to be displayed")
}

Rel(camera, cameraManager, "Captures Images", "USB")
Rel(simpleOutputManager, display, "Output", "HDMI/USB")

@enduml
